package com.complaint;

import jakarta.mail.*;
import org.camunda.bpm.engine.delegate.DelegateExecution;
import org.camunda.bpm.engine.delegate.JavaDelegate;
import org.springframework.stereotype.Component;
import com.complaint.logic.mailLogic;
import java.util.Date;
import io.github.cdimascio.dotenv.Dotenv;
import java.util.Properties;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

@Component
public class complaintMail implements JavaDelegate {
    mailLogic mail = new mailLogic();
    Dotenv dotenv = Dotenv.load();
    @Override
    public void execute(DelegateExecution delegateExecution) throws Exception {
        final String senderEmail = dotenv.get("senderEmail"); //requires valid gmail id
        final String senderPassword = dotenv.get("appPassword"); // app Password generated by google
        final String kundeEmail = (String) delegateExecution.getVariable("email");
        boolean solution = true;

        System.out.println("TLSEmail Start");
        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com"); //SMTP Host
        props.put("mail.smtp.port", "587"); //TLS Port
        props.put("mail.smtp.auth", "true"); //enable authentication
        props.put("mail.smtp.starttls.enable", "true"); //enable STARTTLS

        Authenticator auth = new Authenticator() {

            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(senderEmail, senderPassword);
            }
        };

        Session session = Session.getInstance(props, auth);

        try { // måden vi håndtere om en klage kan løses er gennem en variabel, som kommer fra camunda, som hedder
            // managerSolution. Den eneste måde at en klage bliver lavet som ikke løselig, er hvis en manager
            // har kigget på klagen, og derved bliver variablen sat til false. Variablen styrer så hvilken slags mail, der skal sendes tilbage
            solution = (boolean) delegateExecution.getVariable("managerSolution");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        // Mangler nogle lidt mere specifikke svar, når der sendes email
        if (!solution) {
            mail.sendEmail(session, kundeEmail, "Klage kunne ikke løses", "Din klage kunne desværre ikke løses lige i øjeblikket :)");
        } else {
            mail.sendEmail(session, kundeEmail, "Klage er løst", "Din klage er blevet løst :)");
        }

    }
}